name: Sync remote

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        uses: masesgroup/retrieve-changed-files@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ORACLE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.ORACLE_USER1 }}@${{ secrets.ORACLE_HOST }} "
            cd /home/${{ secrets.ORACLE_USER2 }}/emcs &&
            git pull origin main
          "

      - name: Show changed files
        run: |
          ALL="${{ steps.changes.outputs.all }}"
          MODIFIED="${{ steps.changes.outputs.modified }}"
          ADDED="${{ steps.changes.outputs.added }}"
          DELETED="${{ steps.changes.outputs.deleted }}"
          RENAMED="${{ steps.changes.outputs.renamed }}"

          print_section () {
            NAME="$1"
            DATA="$2"

            if [ -n "$DATA" ]; then
              COUNT=$(echo $DATA | wc -w)
              echo "$NAME [$COUNT]:"
              echo "$DATA"
              echo
            fi
          }

          echo "===== FILE CHANGES ====="
          echo

          print_section "All" "$ALL"
          print_section "Modified" "$MODIFIED"
          print_section "Added" "$ADDED"
          print_section "Deleted" "$DELETED"
          print_section "Renamed" "$RENAMED"

          echo "========================"