name: Deploy to remote

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          ssh -i <(echo "${{ secrets.ORACLE_KEY }}") \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.ORACLE_USER }}@${{ secrets.ORACLE_HOST }} "
              cd /home/${{ secrets.ORACLE_USER }}/emcs &&
              git pull origin main
            "